data=(5,5+5j,4.3,False,None,'string')
data
id(data)
type(data)
dir(data)
data.count(False)
data.index(4.3)
data[-1][3]
data
data=[5,5+6j,4.4,True,False,0,1]
data.count(False)
data.count(True)
data.index(1)
data.append(34)
data
dir(data)
type(data)
data.insert(4,500)
data
data.insert(-1,456)
data
type(data)
data.insert(7,'basil')
data
data.insert(8,None)
data
data.append('fgdd')
data
unit=(45,67.8,True)
data.append(unit)
data
data.insert(6,unit)
data
data.extend(unit)
data
data.pop(3)