use basi;
select* from railway;
SELECT count(`Transaction ID`) from railway;
select distinct `purchase type` from railway;
select count(`journey status`) from railway where `journey status`="On Time";
select distinct `payment method` from railway;
select count(`payment method`)from railway where `payment method`='Contactless';
select count(`payment method`)from railway where `payment method`='Credit Card';
select count(`payment method`)from railway where `payment method`='Debit Card';
select distinct `purchase type` from railway;
select count(`purchase type`)from railway where `purchase type`='online';
select count(`purchase type`)from railway where `purchase type`='Station';
select* from railway;
select distinct railcard from railway;
select count(Railcard)from railway where Railcard='Adult';
select count(railcard)from railway where railcard='None';
select count(railcard)from railway where railcard='Disabled';
select count(railcard)from railway where railcard='Senior';
select* from railway;
select distinct `ticket class` from railway;
select count(`ticket class`)from railway where `ticket class`='Standard';
select count(`ticket class`)from railway where `ticket class`='First Class';
select* from railway;
select distinct`Ticket Type` from railway;
select count(`Ticket Type`)from railway where `Ticket Type`='Advance';
select count(`Ticket Type`)from railway where `Ticket Type`='Standard';
select count(`Ticket Type`)from railway where `Ticket Type`='Anytime';
select* from railway;
select max(price)from railway;
select count(price)from railway where price='267';
select min(price) from railway;
select count(price)from railway where price='1';
select avg(price) from railway;
select sum(price) from railway;
select* from railway;
select  distinct `Departure Station`from railway;
select count( `Departure Station`)from railway;
select count( distinct `Departure Station`)from railway;
select max(`Departure Station`)from railway;
select count(`Departure Station`)from railway where `Departure Station`='York';
select min(`Departure Station`)from railway;
select count(`Departure Station`)from railway where `Departure Station`='Birmingham New Street';
select* from railway;
select  distinct `Arrival Destination`from railway;
select  count( `Arrival Destination`)from railway;
select  count(distinct `Arrival Destination`)from railway;

